name: Deploy to EC2

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup SSH and Deploy to EC2
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.EC2_SSH_KEY }}" | tr -d '\r' > ~/.ssh/id_rsa
        chmod 700 ~/.ssh
        chmod 600 ~/.ssh/id_rsa

        # Add host to known_hosts
        ssh-keyscan ${{ secrets.EC2_HOST }} >> ~/.ssh/known_hosts
        ssh-keyscan github.com >> ~/.ssh/known_hosts

        # Connect and deploy
        ssh -i ~/.ssh/id_rsa ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} << 'EOF'
          cd ~/upstox_bot

          echo "✅ Pulling latest code"
          git pull origin main

          echo "✅ Activating virtual environment"
          source upstox_env/bin/activate

          echo "✅ Installing dependencies"
          pip install -r requirements.txt

          echo "✅ Deployment successful"
        EOF
